### ISSUE TITLE
send line numbers as integers instead of strings? 

### ISSUE THREAD

**Issue by dampier** [mcohen01/crowbar#2]
In sending the stack trace to Rollbar, the `lineno` value for each frame should be an integer; crowbar currently seems to send them as strings — e.g., 

```
        {
          "filename": "rabbit_mq.clj", 
          "lineno": "122", 
          "method": "com.roximity.rounder.components.rabbit-mq/backoff-handler"
        }, 
```

Would it be possible to send, .e.g., `"lineno": 122` instead?

**Comment by mcohen01** [comment]
152658c36bea38ad4e68be5bd6a0d95e16dacf87 is on clojars
